//액션타입
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCESS"
export const PROFILE_ADD_PHOTO = "PROFILE_ADD_PHOTO"
export const PROFILE_CHANGE_NAME = "PROFILE_CHANGE_NAME"